### ISSUE TITLE
make `add config` button visual more intuitive

### ISSUE THREAD

**Issue by fandujar** [hcavarsan/kftray#1]
How is it:
![Screenshot 2023-12-06 at 15 14 19](https://github.com/hcavarsan/kftray/assets/6901387/c86a524f-6b4d-4b34-9a79-318c93330055)

How it would be more intuitive:

![Screenshot 2023-12-06 at 15 25 07](https://github.com/hcavarsan/kftray/assets/6901387/3a0cafb2-b978-4920-aaa1-2e537cb42078)

**Comment by hcavarsan** [comment]
![image](https://github.com/hcavarsan/kftray/assets/30353685/c8cb71b9-4d06-4a5e-ad0f-96c102f9a3e7)


done @fandujar thanks

**Comment by hcavarsan** [comment]
released https://github.com/hcavarsan/kftray/releases/tag/v0.1.25
