### ISSUE TITLE
clear add config input fields after a item added

### ISSUE THREAD

**Issue by fandujar** [hcavarsan/kftray#2]
How to reproduce:

- Click on add config button
- Input port forward information
- Click on add config
- Check that the item was added
- Click on add config button again

Expected:

All input fields cleaned to input a new port-forward.

**Comment by hcavarsan** [comment]
done, will be release in v0.1.25

https://github.com/hcavarsan/kftray/commit/cb8edbff4b2676e44576e30cdb5c3e3ca3ce0212

thanks @fandujar

**Comment by hcavarsan** [comment]
released: https://github.com/hcavarsan/kftray/releases/tag/v0.1.25
