### ISSUE TITLE
kftray on mac: “kftray” cannot be opened because the developer cannot be verified.

### ISSUE THREAD

**Issue by mrfzy00** [hcavarsan/kftray#204]
hi, i just download the kftray this morning, and it seems the mac version download via the main website not verified.

<img width="304" alt="image" src="https://github.com/hcavarsan/kftray/assets/153153975/4291a010-3dd8-460c-bf3f-240f3a88fd79">

any ideas to solve this? 

thanks in advance.

**Comment by hcavarsan** [comment]
hey, to open Kftray you need to allow the app in Mac system settings, go to System Settings -> Privacy & Security and then click in "Open anyway" button

reference: https://support.apple.com/en-gb/guide/mac-help/mh40616/mac

**Comment by mrfzy00** [comment]
thanks, it works!

cheers
