### ISSUE TITLE
Problem windows placement in MacOS 14.x

### ISSUE THREAD

**Issue by calope** [hcavarsan/kftray#242]
Problem when toggle APP using Mac. The windows change the position.

1. Click toggle button in topbar icon several times.

When click the button, the application must be appear.

**Desktop (please complete the following information):**
 - OS: Mac OS 14.5
 - Version v0.11.13

**Additional context**

To get the windows appear,  use contextual menu, "set windows position" -> "reset position"

**Comment by hcavarsan** [comment]
@calope, thank you for the report. Do you use multiple monitors?

I have already fixed an inconsistency to handle invalid window positions, and I will release the update soon. This issue may already be resolved...

**Comment by hcavarsan** [comment]
@calope  new version v0.11.5 has been released with some improvements and fixes related to window position. Please check if it's working better now..

https://github.com/hcavarsan/kftray/releases/tag/v0.11.5

**Comment by calope** [comment]
Thank's a lot. Works perfectly.
