### ISSUE TITLE
Port-forwarding connects but not going anywhere

### ISSUE THREAD

**Issue by rafi-rr** [hcavarsan/kftray#266]
**Describe the bug**
Using KFTray worked fine up until 2 weeks ago, the same configuration does connect but it doesn't reach the services.
Using kubectl does work.
How can I debug this?

**Desktop (please complete the following information):**
 - MacOS Sonoma 14.3
 - Version 0.12.1

Additionally, the tray icon appears twice and blocks the "Apple" menu:
<img width="42" alt="image" src="https://github.com/hcavarsan/kftray/assets/145126116/5ddfc48c-8287-4a32-a28e-a6cb21bfca6c">

**Comment by hcavarsan** [comment]
Hey, do you know if this behavior started in version 0.12.1? Did it work in the previous version?

You can enable debug logs with some environment variables:

RUST_LOG="trace" KFTRAY_DEBUG="true" open /Applications/kftray.app

The logs file will be created in $HOME/.kftray/app.log.

Let me know if you need any more help!

**Comment by rafi-rr** [comment]
Except for the UI issue, I can recreate the problem with 0.11.7 as well so I think this may be related to our Kubernetes deployment. However, standard `kubectl` port-forwarding works.
Is there anything specific that I should look for in the log?

**Comment by hcavarsan** [comment]
@rafi-rr just search for `Error` logs when starting port forwarding to identify the root cause. for less verbose logging, use `RUST_LOG="info"` or `RUST_LOG="debug"` . if you need help, send me the error logs

**Comment by rafi-rr** [comment]
@hcavarsan I'll email you the log.
Just making sure that you saw this bug as well:
<img width="295" alt="image" src="https://github.com/hcavarsan/kftray/assets/145126116/758104fe-6603-4687-b394-2c5635ff21da">

**Comment by hcavarsan** [comment]
hey,  you can send the error logs here in this issue. just try to find the specific port forwarding logs with the error. if you prefer email, send to [hencavarsan@gmail.com](mailto:hencavarsan@gmail.com).


related to the icon bug: my macbook's being repaired and i should check it next week. some users had similar issues with the new version, but many fixed it by restarting the app. i'll test/fix it when my mac's back.

**Comment by rafi-rr** [comment]
@hcavarsan I sent over logs since I couldn't find any errors there.

Regarding the icon, I can recreate it easily and with multiple screen, it just moves between screens.

**Comment by edwardbarford** [comment]
I'm also unable to complete requests.

I had to go back to v11.6 to get it working again.

This is on Windows x64

**Comment by hcavarsan** [comment]
Okay, @edwardbarford, thank you for the feedback. I'll work on this this week.

@rafi-rr, thank you for the logs. Regarding the icon issue, I've opened a separate issue, #268, to track that specific behavior. This will allow us to focus on the port forwarding issue in this thread.

I don't find any errors in the logs. Could you please test the issue in version v0.11.6 to see if it works in the previous version? You can follow these steps to check if there's an issue with the configurations:

1. Export the configurations in the v0.11.6 version.
2. Delete all configurations.
3. Upgrade the kftray to v0.12.1.
4. Import the configurations, close kftray, and open it again.

and see if port forward works.

also, you can provide me with some points to help me reproduce the issue:

1. Send me the logs with `RUST_LOG="trace"` if that's okay with you.
2. Send me the configurations you're trying to use for port forwarding.
3. Send me the manifest from the pod and service for one of these configurations.

If you prefer, you can anonymize some information to provide only examples, just to help me reproduce the issue.

thanks

**Comment by rafi-rr** [comment]
@hcavarsan I can confirm that v0.11.6 works.

**Comment by hcavarsan** [comment]
fixed. could you check if it's working now?

**Comment by rafi-rr** [comment]
@hcavarsan Confirmed. It connects now.
