### ISSUE TITLE
Cannot stop all port forwarding after click "Stop All"

### ISSUE THREAD

**Issue by timslovic** [hcavarsan/kftray#292]
**Describe the bug**
After i started all port forwarding, I got a error when I click "Stop All" and these port forwarding alse not stoped

**To Reproduce**
1. Go to 'Main Window'
2. Click on 'Start All' and waiting all port forwarding started
3. Click on "Stop All"

**Expected behavior**
All port forwarding are stoped.

**Screenshots**
An error occurred while stopping port forwarding: Failed to infer configuration: failed to infer config: in-cluster: (failed to read an incluster environment variable: environment variable not found), kubeconfig: (failed to read kubeconfig from '"~/.kube/config"': No such file or directory (os error 2))
<img width="1004" alt="zm20240824-2106-2" src="https://github.com/user-attachments/assets/c8856098-00a7-4c3d-ab0d-99e0e112b64d">

**Desktop (please complete the following information):**
 - OS: MacOS 
 - Browser Chrome
 - Version 14.6.1

**Additional context**

**Comment by timslovic** [comment]
Updated:
I tried to reproduce the issue using kftui but it works fine

**Comment by hcavarsan** [comment]
Thank you for the report, @timslovic. I'm on it.

**Comment by hcavarsan** [comment]
@timslovic  can you try to see if its ok now?

https://github.com/hcavarsan/kftray/releases/tag/v0.13.3

**Comment by hcavarsan** [comment]
@timslovic hey, any updates on this? could you try with kftray version 0.14.1 ?

**Comment by hcavarsan** [comment]
i think the issue should be fixed now. if you still run into the problem, just reopen this issue and i'll keep looking into it. thanks a lot for the report!
