### ISSUE TITLE
Arm64 container arch?

### ISSUE THREAD

**Issue by andrewscherpbier** [hcavarsan/kftray#308]
**Describe the bug**
When attempting a UDP port forward, the ktray-forward-... pod logs

`exec /kftray-server: exec format error`

I presume because I am on a Mac M1 running minikube and I don't see any code that creates a multi-arch docker images.
For our own containers, we specify `--platform=linux/arm64,linux/amd64` to build multi-arch container images.

**To Reproduce**
1. Buy a Mac M1, M2, M3, or M4 (Not quite!)
2. install kftray through brew
3. create a service with UDP ports in minikube
4. use kftray to port forward one of those UDP ports
5. The kftray-server cannot start because of `exec /kftray-server: exec format error`

**Expected behavior**
UDP port forwarding should work on Mac M1

**Screenshots**
![image](https://github.com/user-attachments/assets/70a85b20-6124-47e0-a8ec-0c0fce3f37eb)

**Desktop (please complete the following information):**
 - OS: macOS 14.7.0 Sonoma
 - Browser: Edge
 - Version: Version 128.0.2739.79 (Official build) (arm64)

**Additional context**
![image](https://github.com/user-attachments/assets/da18f3bf-ef8b-43f5-be06-49bdea96da7e)

**Comment by hcavarsan** [comment]
yeap, makes sense, ill add multi platform build in CI workflow,  im on it
thanks for the report

**Comment by hcavarsan** [comment]
done @andrewscherpbier https://github.com/hcavarsan/kftray/releases/tag/v0.14.5

**Comment by andrewscherpbier** [comment]
Awesome!  Amazing quick work there!  It is now running against my minikube!
