### ISSUE TITLE
Find automatically an available  free local port if the config localport is not set

### ISSUE THREAD

**Issue by lcasavola** [hcavarsan/kftray#310]
Hello,
Is a typical scenario for an user to have to connect in the same kluster context to different services which generally expose the http port 80 ( for example a nodejs or apache and wordpress with a postgresql db handled by a pgadmin service, all these services typically are listening on port 80).
These administrative services should be not exposed on internet so it is supposed to be accessed directly on the cluster through port-forward mechanism. I think it would be cumbersome for an user try a local port , realize later it is laready opened, try another one and so one. 
To indicate the need to find automatically a free port I would suggest to set  the localport config value with a wildcard such as "?" , ".", "*" .
This is the same mechanism available on kubectl where you leave the localport item empy in the syntax local:remote , for example " :80".
The same behaviour is implemented in the defintion of an ak8s service of type service where you can indicate the nodePort explicity

apiVersion: v1
kind: Service
metadata:
  name: somename
  namespace: somenamspace
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: http
   nodePort: 31080

or
you can omit the nodePort attribute and let the the k8s controller choosing a free nodePort for you

**Comment by hcavarsan** [comment]
@lcasavola done: https://github.com/hcavarsan/kftray/releases/tag/v0.14.7

**Comment by lcasavola** [comment]
@hcavarsan: I tested v0.14.7 , 
Initially I got the MS firewall prompt asking me to allow public and private network to access the kftray  
but the redirection with the random local port was not created. Then, after restarting the application, 
all was working correctly.
Good job, thanks for the enhancement.
Rgds
Luca
