### ISSUE TITLE
Add possibility to configure container image repo

### ISSUE THREAD

**Issue by slachiewicz** [hcavarsan/kftray#48]
It would be good to have the possibility to configure the used proxy image
https://github.com/hcavarsan/kftray/blob/main/src-tauri/utils/kubeforward/src/proxy.rs#L70
to use in air-gapped environments.

Also sometimes Kubernetes has restrictions or requirements to add CPU&mem request/limits, taints or labels

**Comment by hcavarsan** [comment]
makes sense! ill work on it and keep you updated.

**Comment by hcavarsan** [comment]
@slachiewicz 

done! will be released in v0.5.5

kftray server  pod manifest is now located at `$HOME/.kftray/proxy_manifest.json` and is editable.

just a note: modifying placeholder `{}` fields or changing expected configurations may disrupt proxy port forwarding functionality.

Thanks for the feedback!. Please report any issues encountered.

**Comment by hcavarsan** [comment]
https://github.com/hcavarsan/kftray/releases/tag/v0.5.5
