### ISSUE TITLE
Add option to edit a port-forward

### ISSUE THREAD

**Issue by fandujar** [hcavarsan/kftray#8]
Add an action to edit a port-forward

**Comment by hcavarsan** [comment]
done @fandujar, will be release in v0.1.40, thanks!

![image](https://github.com/hcavarsan/kftray/assets/30353685/ee55ad26-055a-4ecc-97f1-1339ac49de4f)
![image](https://github.com/hcavarsan/kftray/assets/30353685/c7e9a7cb-e3a1-436e-8e3c-621ddddbbbfa)
